DROP TABLE IF EXISTS "CONV_GRADUATION_STUDENT_RECORD";
CREATE TABLE "CONV_GRADUATION_STUDENT_RECORD"
(
    "GRADUATION_STUDENT_RECORD_ID" RAW(16) NOT NULL,
    "GRADUATION_PROGRAM_CODE" VARCHAR(8 ),
    "PROGRAM_COMPLETION_DATE" DATE,
    "GPA" NUMBER(5,4),
    "HONOURS_STANDING" VARCHAR(1),
    "RECALCULATE_GRAD_STATUS" VARCHAR(1),
    "STUDENT_GRAD_DATA" CLOB,
    "SCHOOL_OF_RECORD" VARCHAR(9),
    "SCHOOL_AT_GRADUATION" VARCHAR(9),
    "STUDENT_GRADE" VARCHAR(3),
    "STUDENT_STATUS_CODE" VARCHAR(1),
    "CREATE_USER" VARCHAR(20) DEFAULT 'TestUser',
    "CREATE_DATE" DATE DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_USER" VARCHAR(20) DEFAULT 'TestUser',
    "UPDATE_DATE" DATE DEFAULT CURRENT_TIMESTAMP
);