-- Data conversion schema creation
DROP TABLE IF EXISTS "CONV_GRADUATION_STUDENT_RECORD";
CREATE TABLE "CONV_GRADUATION_STUDENT_RECORD"
   (
	"GRADUATION_STUDENT_RECORD_ID" RAW(16) NOT NULL,
    "GRADUATION_PROGRAM_CODE" VARCHAR2(8 BYTE),
    "PROGRAM_COMPLETION_DATE" DATE,
    "GPA" NUMBER(5,4),
    "HONOURS_STANDING" VARCHAR2(1 BYTE),
    "RECALCULATE_GRAD_STATUS" VARCHAR2(1 BYTE),
    "STUDENT_GRAD_DATA" CLOB,
    "SCHOOL_OF_RECORD" VARCHAR2(9 BYTE),
    "SCHOOL_AT_GRADUATION" VARCHAR2(9 BYTE),
    "STUDENT_GRADE" VARCHAR2(3 BYTE),
    "STUDENT_STATUS_CODE" VARCHAR2(1 BYTE),
	"CREATE_USER" VARCHAR2(20 BYTE) DEFAULT USER,
	"CREATE_DATE" DATE DEFAULT systimestamp,
	"UPDATE_USER" VARCHAR2(20 BYTE) DEFAULT USER,
	"UPDATE_DATE" DATE DEFAULT systimestamp
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "API_GRAD_BLOB_DATA"   NO INMEMORY
 LOB ("STUDENT_GRAD_DATA") STORE AS SECUREFILE (
  TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

 --------------------------------------------------------
 --  Constraints for Table GRAD_STUDENT
 --------------------------------------------------------
   ALTER TABLE "CONV_GRADUATION_STUDENT_RECORD" MODIFY ("CREATE_USER" NOT NULL ENABLE);
   ALTER TABLE "CONV_GRADUATION_STUDENT_RECORD" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
   ALTER TABLE "CONV_GRADUATION_STUDENT_RECORD" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
   ALTER TABLE "CONV_GRADUATION_STUDENT_RECORD" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
   ALTER TABLE "CONV_GRADUATION_STUDENT_RECORD" MODIFY ("GRADUATION_PROGRAM_CODE" NOT NULL ENABLE);
   ALTER TABLE "CONV_GRADUATION_STUDENT_RECORD" MODIFY ("GRADUATION_STUDENT_RECORD_ID" NOT NULL ENABLE);
   ALTER TABLE "CONV_GRADUATION_STUDENT_RECORD" ADD CONSTRAINT "CONV_GRADUATION_STUDENT_RECORD_PK" PRIMARY KEY ("GRADUATION_STUDENT_RECORD_ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
   STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "API_GRAD_BLOB_DATA"  ENABLE;


--------------------------------------------------------
--  DDL for Table GRAD_STUDENT_SPECIAL_PROGRAMS
--------------------------------------------------------

CREATE TABLE "CONV_STUDENT_OPTIONAL_PROGRAM"
(	"STUDENT_OPTIONAL_PROGRAM_ID" RAW(16) DEFAULT SYS_GUID(),
     "OPTIONAL_PROGRAM_ID" RAW(16),
     "GRADUATION_STUDENT_RECORD_ID" RAW(16),
     "COMPLETION_DATE" DATE,
     "PROGRAM_NOTE" CLOB,
     "CREATE_USER" VARCHAR2(20 BYTE) DEFAULT USER,
     "CREATE_DATE" DATE DEFAULT systimestamp,
     "UPDATE_USER" VARCHAR2(20 BYTE) DEFAULT USER,
     "UPDATE_DATE" DATE DEFAULT systimestamp
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "API_GRAD_BLOB_DATA"   NO INMEMORY
 LOB ("PROGRAM_NOTE") STORE AS SECUREFILE (
  TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

--------------------------------------------------------
--  Constraints for Table GRAD_STUDENT_SPECIAL_PROGRAMS
--------------------------------------------------------

ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" MODIFY ("OPTIONAL_PROGRAM_ID" NOT NULL ENABLE);
ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" MODIFY ("GRADUATION_STUDENT_RECORD_ID" NOT NULL ENABLE);
ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" MODIFY ("CREATE_USER" NOT NULL ENABLE);
ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" ADD CONSTRAINT "CONV_GRAD_STUDENT_SPECIAL_PROGRAMS_PK" PRIMARY KEY ("STUDENT_OPTIONAL_PROGRAM_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "API_GRAD_BLOB_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRAD_STUDENT_SPECIAL_PROGRAMS
--------------------------------------------------------

ALTER TABLE "CONV_STUDENT_OPTIONAL_PROGRAM" ADD CONSTRAINT "FK_CONV_GRADUATION_STUDENT_RECORD" FOREIGN KEY ("GRADUATION_STUDENT_RECORD_ID")
    REFERENCES "CONV_GRADUATION_STUDENT_RECORD" ("GRADUATION_STUDENT_RECORD_ID") ENABLE;

------------------------------
-- Initial data set from TRAX
------------------------------
-- GRAD_STUDENT
select  trim(m.stud_no) as PEN, m.mincode as SCHOOL_OF_RECORD, m.mincode_grad as SCHOOL_AT_GRAD, m.stud_grade as STUD_GRADE, m.stud_status as STUD_STATUS, '2018-EN', 'Y'
from trax_students_load l, student_master m
where 1 = 1
and l.stud_no = m.stud_no
--and m.grad_date = 0
--and m.archive_flag = 'A'

-- GRAD_COURSE_RESTRICTIONS
select trim(c1.crse_code) as CRSE_MAIN, trim(c1.crse_level) as CRSE_MAIN_LVL,
 trim(c2.crse_code) as CRSE_RESTRICTED, trim(c2.crse_level) as CRSE_RESTRICTED_LVL,
 trim(c1.start_restrict_session) as RESTRICTION_START_DT, trim(c1.end_restrict_session) as RESTRICTION_END_DT
from tab_crse c1
join tab_crse c2
on c1.restriction_code = c2.restriction_code
and (c1.crse_code  <> c2.crse_code
 or  c1.crse_level <> c2.crse_level)
and c1.restriction_code <> ' '

------------------------------
-- Validation Queries
------------------------------
-- French immersion validation by pen
select count(*) from STUD_XCRSE sx, COURSE_REQUIREMENT cr
where 1 = 1
  and sx.stud_no = '131493553'  -- pen
  and trim(sx.crse_code) = cr.course_code
  and trim(sx.crse_level) = cr.course_level
  and cr.course_requirement_code = 202
