-- API_GRAD_DATA_CONV.TRAX_UPDATED_SUB_EVENT definition

CREATE TABLE "TRAX_UPDATED_SUB_EVENT"
   (	"REPLICATION_EVENT_ID" RAW(16) NOT NULL ENABLE,
	"EVENT_ID" RAW(16) NOT NULL ENABLE,
	"EVENT_PAYLOAD" BLOB NOT NULL ENABLE,
	"EVENT_STATUS" VARCHAR2(50) NOT NULL ENABLE,
	"EVENT_TYPE" VARCHAR2(100) NOT NULL ENABLE,
    "ACTIVITY_CODE" VARCHAR2(15 BYTE),
    "EVENT_OUTCOME" VARCHAR2(100) NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(32),
	"CREATE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_USER" VARCHAR2(32),
	"UPDATE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	 CONSTRAINT "TRAX_UPDATED_SUB_EVENT_PK" PRIMARY KEY ("REPLICATION_EVENT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
	 CONSTRAINT "TRAX_UPDSUB_EVENT_ID_UK" UNIQUE ("EVENT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY
 LOB ("EVENT_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW CHUNK 8192) ;

CREATE INDEX "TRAX_UPDATED_SUB_EVENT_STATUS_IDX" ON "TRAX_UPDATED_SUB_EVENT" ("EVENT_STATUS")
  TABLESPACE "API_GRAD_IDX" ;

CREATE INDEX "TRAX_UPDATED_SUB_EVENT_TYPE_IDX" ON "TRAX_UPDATED_SUB_EVENT" ("EVENT_TYPE")
  TABLESPACE "API_GRAD_IDX" ;

COMMENT ON TABLE TRAX_UPDATED_SUB_EVENT IS 'This table is used to store all the received choreographed events from different api via pub/sub model and process them.';

-- API_GRAD_DATA_CONV.EVENT_SHEDLOCK definition

CREATE TABLE "EVENT_SHEDLOCK"
   (	"NAME" VARCHAR2(64),
	"LOCK_UNTIL" TIMESTAMP (3),
	"LOCKED_AT" TIMESTAMP (3),
	"LOCKED_BY" VARCHAR2(255),
	 CONSTRAINT "EVENT_SHEDLOCK_PK" PRIMARY KEY ("NAME")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

COMMENT ON TABLE EVENT_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

