GRANT SELECT ON BATCH_JOB_EXECUTION TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION_CONTEXT TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION_PARAMS TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_INSTANCE TO GRAD_READONLY;
GRANT SELECT ON BATCH_STEP_EXECUTION TO GRAD_READONLY;
GRANT SELECT ON BATCH_STEP_EXECUTION_CONTEXT TO GRAD_READONLY;
GRANT SELECT ON EVENT_SHEDLOCK TO GRAD_READONLY;
GRANT SELECT ON FLYWAY_SCHEMA_HISTORY TO GRAD_READONLY;
GRANT SELECT ON TRAX_UPDATED_SUB_EVENT TO GRAD_READONLY;



