#Keycloak/OAuth properties
security:
  oauth2:
    resource:
      jwt:
        key-value: ${KEYCLOAK_PUBLIC_KEY}

#DB Properties
spring:
  jmx:
    enabled: false
  db-connection:
    url: ${CONNECTION_STRING}
    driver-class: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    assessment:
      username: ${ASSESSMENT_USERNAME}
      password: ${ASSESSMENT_PASSWORD}
      pool-name: conv-assessment-cp
    batch:
      username: ${BATCH_USERNAME}
      password: ${BATCH_PASSWORD}
      pool-name: conv-batch-cp
    conv:
      username: ${CONV_USERNAME}
      password: ${CONV_PASSWORD}
      pool-name: conv-data-conv-cp
    course:
      username: ${COURSE_USERNAME}
      password: ${COURSE_PASSWORD}
      pool-name: conv-course-cp
    program:
      username: ${PROGRAM_USERNAME}
      password: ${PROGRAM_PASSWORD}
      pool-name: conv-program-cp
    student:
      username: ${STUDENT_USERNAME}
      password: ${STUDENT_PASSWORD}
      pool-name: conv-student-cp
    trax:
      username: ${TRAX_USERNAME}
      password: ${TRAX_PASSWORD}
      pool-name: conv-trax-cp
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: ${API_USERNAME}
      password: ${API_PASSWORD}
  batch:
    initialize-schema: NEVER
    job:
      enabled: false
  flyway:
    enabled: ${ENABLE_FLYWAY}
    baseline-on-migrate: false
    table: FLYWAY_SCHEMA_HISTORY
    url: ${CONNECTION_STRING}
    schema: ${CONV_USERNAME}
    user: ${CONV_USERNAME}
    password: ${CONV_PASSWORD}
    location: classpath:db/migration

#Logging properties
logging:
  file:
    max-history: 1
    clean-history-on-start: true
    max-size: 20MB
    name: /logs/app.log
  #pattern:
  #  file: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  #  console: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              dataconversion: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}

authorization:
  user: ${GRAD_CLIENT_NAME}
  password: ${GRAD_CLIENT_SECRET}

#Endpoints
endpoint:
  keycloack:
    getToken: https://soam-tools.apps.silver.devops.gov.bc.ca/auth/realms/master/protocol/openid-connect/token
  pen-student-api:
    by-pen:
      url: https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/api/v1/student?pen=%s
  grad-program-api:
    special-program:
      url: https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/program/optionalprograms
